### ISSUE TITLE
Invalid customer branch version resolution

### ISSUE THREAD

**Issue by simPod** [malukenho/mcbumpface#20]
When having dependency defined as `"vendor/package": "dev-branch-name@dev",` it changes it to `"vendor/package": "^dev-branch-name",`.

The expected result is to keep it as is.

composer.lock has this content:

```
        {
            "name": "vendor/package",
            "version": "dev-branch-name",
```

Interestingly, it seems to work with `master` branch: `"vendor/package": "dev-master@dev",`. This does not get changed.

**Comment by simPod** [comment]
It will be this line https://github.com/malukenho/mcbumpface/blob/b8ffb816e7e921fd6b7f85cbf2f11b9d550f3e2d/src/BumpInto.php#L90

**Comment by malukenho** [comment]
Amazing work @simPod! Thank you.
