### ISSUE TITLE
Range constraint support

### ISSUE THREAD

**Issue by ostrolucky** [malukenho/mcbumpface#24]
I would say following should not happen:
```
malukenho/mcbumpface is updating mongodb/mongodb package from version (^1.3.0, <1.4.0) to (^1.3.2)
```

**Comment by rob006** [comment]
Same for:

```
malukenho/mcbumpface is updating yiisoft/yii2 package from version (~2.0.23) to (^2.0.32)
```

This is huge blocker for using this plugin.

**Comment by malukenho** [comment]
Well, I can understand it is a problem on the first reported case, but for your specific case @rob006, what is the impact of that? I mean, I would expect it to be fine.

**Comment by rob006** [comment]
@malukenho It is exact the same problem, only different syntax. `~2.0.23` is equivalent to `>=2.0.23, <2.1.0` while `^2.0.23` is equivalent to `>=2.0.23, <3.0.0`. So `~2.0.23` disallows `2.1.0` release while `^2.0.23` is fine with it. This plugin should not touch upper version limit in constraint, only bump lower version.

**Comment by malukenho** [comment]
@rob006 can you check #28?

@ostrolucky it is not a proper solution, but at least it gets out of the way until I have a better one.

**Comment by malukenho** [comment]
It should be fine for those cases now on `1.1.1`
