### ISSUE TITLE
Switching `stripVersionPrefixes` from false to true does not remove prefixes

### ISSUE THREAD

**Issue by bendavies** [malukenho/mcbumpface#36]
If no deps are updated, switching `stripVersionPrefixes` from false to true does not remove prefixes. It would be nice to strip prefixes even if no updates are made.

**Comment by malukenho** [comment]
We only touch packages that are being updated by composer under the current `composer update` process, I'm not sure if I want to change that 🤔

**Comment by malukenho** [comment]
I'll close it for now but I might think more about it in the future. Thank you for the contribution @bendavies 😊
