### ISSUE TITLE
^2@dev is incorrectly changed to ^2.x-dev

### ISSUE THREAD

**Issue by ostrolucky** [malukenho/mcbumpface#40]
```
malukenho/mcbumpface is updating ruflin/elastica package from version (^2@dev) to (^2.x-dev)
```

**Comment by boesing** [comment]
Yeah, branch-aliases are only available as-is.
I think, skipping `@dev` dependencies should be skipped anyways, as `@dev` forces composer to ignore stability configuration for that specific package.

**Comment by malukenho** [comment]
Thank you @ostrolucky!

**Comment by ostrolucky** [comment]
Thank you for fixing it @malukenho!
